#!/bin/sh
### BEGIN INIT INFO
# Provides:          tailscale
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tailscale VPN service
### END INIT INFO

DAEMON=/usr/bin/tailscaled
DAEMON_ARGS=""
PIDFILE=/var/run/tailscale/tailscaled.pid
LOGFILE=/var/log/tailscale.log

case "$1" in
  start)
    echo "Starting Tailscale..."
    start-stop-daemon --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS >> $LOGFILE 2>&1
    ;;
  stop)
    echo "Stopping Tailscale..."
    start-stop-daemon --stop --pidfile $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ]; then
      echo "Tailscale is running."
    else
      echo "Tailscale is not running."
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
